development:
  adapter: postgresql
  encoding: unicode
  database: ogma_development
  username: postgres
  password: password
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: ogma_test
  username: postgres
  password: password
  encoding: UTF8
  pool: 5
  timeout: 5000