development:
  adapter: postgresql
  encoding: unicode
  database: icms_kskb_development
  host: localhost
  username: postgres
  password: password
  encoding: UTF8
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: ogma_test
  host: localhost
  username: postgres
  password: password
  encoding: UTF8
  pool: 5
  timeout: 5000